### ISSUE TITLE
Make pandoc.Wait(5) time adjustable

### ISSUE THREAD

**Issue by jmooo** [Maboroshy/Note-Station-to-markdown#15]
A few of my notes were triggering this error, which appears to be a 5s wait for pandoc to do its thing:

```
Traceback (most recent call last):
  File "./nsx2md.py", line 133, in <module>
    pandoc.wait(5)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1616, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['pandoc', '-f', 'html', '-t', 'markdown_strict+pipe_tables-raw_html', '--wrap=none', '--atx-headers', '-o', '/var/folders/gg/8fhvnc85693bnnpcw53k1jt80000gn/T/tmpqskz8j8t', '/var/folders/gg/8fhvnc85693bnnpcw53k1jt80000gn/T/tmpvw_o1sn3']' timed out after 5 seconds
```

I solved it by changing the wait to 20s:
```
pandoc = subprocess.Popen(pandoc_args)
pandoc.wait(20)
```

Maybe the delay could be extended by default, or just break it out as a setting like the other options at the top of the file?

Thanks a million the script works great! I'm using it to migrate from DS Note to Joplin currently

**Comment by Maboroshy** [comment]
I've changed the timeout to 20. Thanks!
